using System;
using System.Net.Mime;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Plugin.YouTubeSync.Metadata;
using Jellyfin.Plugin.YouTubeSync.Playback;
using Jellyfin.Plugin.YouTubeSync.Services;
using Jellyfin.Plugin.YouTubeSync.Sync;
using MediaBrowser.Common.Api;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.YouTubeSync.Controllers;

/// <summary>
/// HTTP API controller for YouTube playback and the configuration page.
///
/// Endpoints:
/// <list type="bullet">
/// <item><c>GET /YouTubeSync/resolve/{videoId}</c> – anonymous; resolves a video to a playback URL and redirects (302).</item>
/// <item><c>GET /YouTubeSync/session/{sessionId}/{fileName}</c> – anonymous; serves managed-transcoding HLS files.</item>
/// <item><c>GET /YouTubeSync/source-info?url=…</c> – administrators only; fetches channel/playlist metadata for the dashboard.</item>
/// </list>
///
/// The .strm files generated by <see cref="SyncService"/> point to the resolve endpoint.
/// Jellyfin (or the client) fetches that URL without any access token when playback starts,
/// so the playback endpoints must stay anonymous. The metadata endpoint launches yt-dlp on
/// the server and is therefore restricted to elevated users.
/// </summary>
[ApiController]
[Route("YouTubeSync")]
[Produces(MediaTypeNames.Application.Json)]
public class YouTubeSyncController : ControllerBase
{
    private readonly ResolveService _resolveService;
    private readonly ManagedTranscodeService _managedTranscodeService;
    private readonly YtDlpService _ytDlpService;
    private readonly ILogger<YouTubeSyncController> _logger;

    /// <summary>Initializes a new instance of the <see cref="YouTubeSyncController"/> class.</summary>
    public YouTubeSyncController(
        ResolveService resolveService,
        ManagedTranscodeService managedTranscodeService,
        YtDlpService ytDlpService,
        ILogger<YouTubeSyncController> logger)
    {
        _resolveService = resolveService;
        _managedTranscodeService = managedTranscodeService;
        _ytDlpService = ytDlpService;
        _logger = logger;
    }

    /// <summary>
    /// Resolves a YouTube video ID to a direct playback URL and returns an HTTP 302 redirect.
    /// Returns 503 when no compatible playback format is available.
    /// </summary>
    /// <param name="videoId">The YouTube video ID (e.g. dQw4w9WgXcQ).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>302 redirect or 503 if no compatible format is found.</returns>
    [HttpGet("resolve/{videoId}")]
    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status302Found)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> ResolveVideo(string videoId, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(videoId) || videoId.Length > 32)
        {
            return BadRequest("Invalid video ID.");
        }

        _logger.LogInformation("Resolve request for video {VideoId}", videoId);

        if (Plugin.Instance?.Configuration.AllowManagedTranscoding == true)
        {
            var sessionPath = await _managedTranscodeService.TryCreateSessionAsync(videoId, cancellationToken).ConfigureAwait(false);
            if (!string.IsNullOrWhiteSpace(sessionPath))
            {
                _logger.LogInformation("Using managed transcoding session for video {VideoId}", videoId);
                return LocalRedirect(sessionPath);
            }

            _logger.LogInformation("Managed transcoding unavailable for {VideoId}; falling back to direct resolve path.", videoId);
        }

        var url = await _resolveService.ResolveAsync(videoId, cancellationToken).ConfigureAwait(false);
        if (string.IsNullOrWhiteSpace(url))
        {
            _logger.LogWarning(
                "No compatible playback format available for {VideoId}. Returning 503.",
                videoId);
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                $"No compatible playback URL found for video '{videoId}'.");
        }

        return Redirect(url);
    }

    /// <summary>
    /// Serves managed-transcoding HLS playlists and segment files.
    /// </summary>
    [HttpGet("session/{sessionId}/{fileName}")]
    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public IActionResult GetManagedSessionFile(string sessionId, string fileName)
    {
        if (!_managedTranscodeService.TryGetSessionFile(sessionId, fileName, out var filePath, out var contentType))
        {
            return NotFound();
        }

        if (fileName.EndsWith(".m3u8", StringComparison.OrdinalIgnoreCase))
        {
            Response.Headers.CacheControl = "no-store, no-cache, must-revalidate";
            Response.Headers.Pragma = "no-cache";
            Response.Headers.Expires = "0";
        }

        return PhysicalFile(filePath, contentType, enableRangeProcessing: false);
    }

    /// <summary>
    /// Fetches metadata (title, description, thumbnail URL, type) for a YouTube channel or playlist URL.
    /// Called by the admin configuration UI to auto-populate source details.
    /// Requires an elevated (administrator) session because it runs yt-dlp on the server.
    /// </summary>
    /// <param name="url">The YouTube channel or playlist URL.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A <see cref="SourceInfo"/> object, or 400/401/403/503 on error.</returns>
    [HttpGet("source-info")]
    [Authorize(Policy = Policies.RequiresElevation)]
    [ProducesResponseType(typeof(SourceInfo), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> GetSourceInfo([FromQuery] string url, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return BadRequest("url query parameter is required.");
        }

        _logger.LogInformation("Source-info request for URL {Url}", url);

        var info = await _ytDlpService.GetSourceInfoAsync(url, cancellationToken).ConfigureAwait(false);
        if (info is null)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                "Failed to fetch source info from YouTube. Check that yt-dlp is installed and the URL is valid.");
        }

        return Ok(info);
    }
}

